### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by pittbull** [uphillbattle/NettleieElvia#3]
Hi.

Found your code and wanted to test it out on my appdaemon, but I get the following error:

```
2022-07-09 18:53:52.199027 WARNING nettleie_elvia: ------------------------------------------------------------
--
2022-07-09 18:53:52.198939 WARNING nettleie_elvia: Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/appdaemon/threading.py", line 904, in worker funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"])) File "/conf/apps/nettleie_elvia.py", line 22, in hourly_call self.set_states() File "/conf/apps/nettleie_elvia.py", line 91, in set_states self.priceInfo = self.maler_response["gridTariffCollections"][0]["gridTariff"]["tariffPrice"] TypeError: 'NoneType' object is not subscriptable
2022-07-09 18:53:52.198676 WARNING nettleie_elvia: ------------------------------------------------------------
2022-07-09 18:53:52.198496 WARNING nettleie_elvia: Worker Ags: {'id': '2cb9a4e24afa49339338e2c09b1c2af1', 'name': 'nettleie_elvia', 'objectid': '80efcaa027e447caa22fd0b3c3076cee', 'type': 'scheduler', 'function': <bound method NettleieElvia.hourly_call of <nettleie_elvia.NettleieElvia object at 0x14c33ba11be0>>, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2022-07-09 18:53:52.198343 WARNING nettleie_elvia: Unexpected error in worker for App nettleie_elvia:


```

**Comment by uphillbattle** [comment]
Hi,

Thank you for reporting!

Are these the Home Assistant logs? If so, could you also post the logs from the AppDaemon add-in?

Further, have you tested the API on https://elvia.portal.azure-api.net/docs/services/gridtariffapi/operations/post-digin-api-v-tariffquery-meteringpointsgridtariffs? to check that you have the right X-API-Key and meteringPointId?

**Comment by pittbull** [comment]
Hi. 

These are from appdaemon actually and is reported as soon as appdamoen loads. No sensors are showing in HA. 

I will check the IDs to make sure they are correct. 


//UlfThomas

**Comment by pittbull** [comment]
Verified - and changed the meter id - and now a different error message is reported:


```
2022-07-10 11:42:59.263869 WARNING nettleie_elvia: ------------------------------------------------------------
--
2022-07-10 11:42:59.263373 WARNING nettleie_elvia: Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/appdaemon/threading.py", line 904, in worker funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"])) File "/conf/apps/nettleie_elvia.py", line 22, in hourly_call self.set_states() File "/conf/apps/nettleie_elvia.py", line 91, in set_states self.priceInfo = self.maler_response["gridTariffCollections"][0]["gridTariff"]["tariffPrice"] KeyError: 'gridTariffCollections'
2022-07-10 11:42:59.261606 WARNING nettleie_elvia: ------------------------------------------------------------
2022-07-10 11:42:59.261282 WARNING nettleie_elvia: Worker Ags: {'id': '722de9619d0b4b4084790120904151b0', 'name': 'nettleie_elvia', 'objectid': 'ab0fec321de54d5786d2d1bab29d20ad', 'type': 'scheduler', 'function': <bound method NettleieElvia.hourly_call of <nettleie_elvia.NettleieElvia object at 0x150c783ad730>>, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2022-07-10 11:42:59.260977 WARNING nettleie_elvia: Unexpected error in worker for App nettleie_elvia:
2022-07-10 11:42:59.260636 WARNING nettleie_elvia: ------------------------------------------------------------


```

**Comment by pittbull** [comment]
And as always the error is on the user.

I had not declared the api and målerid as string. When doing so everything reports correctly.

Thank you for the effort and troubleshooting assistance.

**Comment by uphillbattle** [comment]
Sorry for taking time to respond; vacation time 😃

I'm glad to hear you solved it! I should perhaps make a note in the README that the key and meterid should be strings.
